# -*- coding: utf-8 -*-
"""KP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FGqfV3nyGUt3UZZMmPZH-29s-0SbGVl
"""

# Define the probabilities
P_I = 1/2    # Probability of drawing from Bag-I
P_II = 1/2   # Probability of drawing from Bag-II
P_R_given_I = 7/9   # Probability of drawing a red ball from Bag-I
P_R_given_II = 5/14   # Probability of drawing a red ball from Bag-II

# Calculate the overall probability of drawing a red ball
P_R = P_R_given_I * P_I + P_R_given_II * P_II

# Calculate the probability of drawing from Bag-I given that it was red
P_I_given_R = P_R_given_I * P_I / P_R

# Print the result
print("The probability that the ball was from Bag-I given that it was red is:", P_I_given_R)